name: backend

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -e ./backend
          python -m pip install pytest requests pillow pika uvicorn

      - name: Run E2E tests
        env:
          RABBITMQ_HOST: 127.0.0.1
        run: |
          pytest -m e2e -s
